import LegalPage, { LEGAL_UPDATED } from '../components/LegalPage';

/**
 * The privacy policy, and one of the two links Google's consent screen points at.
 *
 * Written from the schema, so every statement is something the code actually does. A policy
 * describing a different system than the one running is worse than none, because it is a
 * commitment nobody is keeping.
 *
 * Plain, standard register throughout. This is the one part of the portal that is not
 * allowed a voice: it is read by people deciding whether to trust us with a resume, and by
 * Google before they approve the OAuth client.
 */
export default function Privacy() {
  return (
    <LegalPage title="Privacy policy" eyebrow="Member Portal">
      <p className="legal-lede">
        This policy applies to the ColorStack at GSU member portal at
        members.colorstackatgsu.com. It does not apply to our public website, our Discord
        server, or services operated by ColorStack Inc.
      </p>
      <p className="legal-meta">Last updated {LEGAL_UPDATED}</p>

      <h2>1. Who we are</h2>
      <p>
        ColorStack at Georgia State University is a registered student organization at
        Georgia State University. For any question about this policy or about your
        information, contact us at{' '}
        <a href="mailto:official@colorstackatgsu.com">official@colorstackatgsu.com</a>.
      </p>

      <h2>2. Information we collect</h2>
      <p>We collect the following information about members.</p>
      <ul>
        <li>
          <strong>Information you provide on the membership form:</strong> your name, GSU
          student email address, personal email address, pronouns, major or majors, class
          year, expected graduation term and year, LinkedIn profile, Discord username, any
          dietary restrictions or allergies you disclose for chapter events, your stated
          plans after graduation, and your stated level of interest in chapter programming.
          We retain the original form submission as received.
        </li>
        <li>
          <strong>Information you provide in the portal:</strong> your resume, a profile
          photograph, a GitHub profile, and any changes you make to the information above.
        </li>
        <li>
          <strong>Information generated by your use of the portal:</strong> records of
          sign-in attempts, one-time verification codes issued to you and the time they were
          issued, whether your account has been activated, and a record of your attendance
          if you check in at a chapter event using a QR code.
        </li>
      </ul>

      <h2>3. How we use your information</h2>
      <p>We use it to:</p>
      <ul>
        <li>administer your membership and operate the portal;</li>
        <li>verify your identity and sign you in;</li>
        <li>
          share your resume and contact information with the companies that sponsor the
          chapter, as described in section 4;
        </li>
        <li>
          communicate with you about your account, chapter events and chapter programming;
        </li>
        <li>
          generate an automated assessment of your resume, if you request one; and
        </li>
        <li>understand chapter attendance and membership in aggregate.</li>
      </ul>

      <h2>4. Disclosure to sponsors</h2>
      <p>
        The chapter maintains a resume book that is made available to companies that sponsor
        ColorStack at GSU. If you have uploaded a resume, it is included.
      </p>
      <p>Sponsors at eligible sponsorship levels can view the following about each member:</p>
      <ul>
        <li>name;</li>
        <li>major or majors, class year, and expected graduation;</li>
        <li>LinkedIn profile, if provided;</li>
        <li>
          an email address for contacting you, which is your personal email address where
          you have provided one and otherwise your student email address; and
        </li>
        <li>your resume, if you have uploaded one.</li>
      </ul>
      <p>
        Sponsors may contact you directly using that address. Sponsors cannot view your
        Discord username, dietary restrictions, stated interests, plans after graduation, or
        your original form submission.
      </p>
      <p>
        Inclusion in the resume book is a condition of the member portal and cannot be
        disabled individually. If you do not want your resume shared with sponsors, you may
        delete it from the resume page at any time, which removes it from the resume book.
        Deleting your resume does not affect your membership. To have your contact
        information withheld from sponsors, contact us at the address in section 1.
      </p>

      <h2>5. Signing in with Google</h2>
      <p>
        If you sign in using Google, Google provides us with your email address, your name,
        and confirmation that Google has verified the address belongs to you. We request no
        other information and receive no other information. We do not receive your Google
        password and have no access to your Gmail, Google Drive, contacts or calendar.
      </p>
      <p>
        We use the address only to match you to an existing membership and sign you in. If
        it does not match a membership, no account is created and no information is
        retained.
      </p>

      <h2>6. Other recipients</h2>
      <ul>
        <li>
          <strong>Chapter officers</strong> have access to all information described in
          section 2 in order to administer the chapter.
        </li>
        <li>
          <strong>Service providers</strong> process information on our behalf: Supabase
          (database and file storage), Railway (application hosting), Google Workspace
          (email delivery and form responses), and Google Gemini (automated resume
          assessment, only when you request one). They are permitted to process your
          information only to provide those services.
        </li>
        <li>
          <strong>Discord</strong> receives your username if you choose to link your Discord
          account, so that we can assign your member role.
        </li>
        <li>
          We may disclose information where required by law or by Georgia State University
          policy.
        </li>
      </ul>
      <p>
        We do not sell your information and we do not disclose it to recruiters or other
        third parties who do not sponsor the chapter.
      </p>

      <h2>7. Retention</h2>
      <p>
        We retain your information for as long as you remain a member and for as long as the
        chapter has a legitimate administrative need for it. One-time verification codes
        expire within one hour of being issued. If you ask us to delete your account, we will
        do so within a reasonable period, retaining only what is necessary for the chapter's
        own records.
      </p>

      <h2>8. Your choices</h2>
      <ul>
        <li>You can review and correct most of your information on the profile page.</li>
        <li>You can delete your resume or profile photograph at any time.</li>
        <li>You can request a copy of the information we hold about you.</li>
        <li>You can request deletion of your account.</li>
      </ul>
      <p>
        For the last two, contact{' '}
        <a href="mailto:official@colorstackatgsu.com">official@colorstackatgsu.com</a>.
      </p>

      <h2>9. Security</h2>
      <p>
        Resumes are held in private storage and are served only through links that expire
        after a short period. Access rules are enforced at the database level rather than
        only in the application. No system is completely secure, and we cannot guarantee
        that your information will never be accessed without authorization. If a breach
        affects your information, we will notify you.
      </p>

      <h2>10. Age</h2>
      <p>
        The portal is intended for enrolled Georgia State University students. It is not
        directed to children under 13, and we do not knowingly collect information from
        them. If you are under 18, please review this policy with a parent or guardian.
      </p>

      <h2>11. Changes to this policy</h2>
      <p>
        We may update this policy from time to time. If we make a material change, we will
        notify members by email and update the date at the top of this page.
      </p>
    </LegalPage>
  );
}
