// GENERATED by scripts/build-mosaic.mjs. Do not edit by hand.
// 14 tiles, 332 KB total.

export const MOSAIC_VERSION = 'v1';

export const MOSAIC_TILES = [
  'chapter-group',
  'chapter-students',
  'atl-mixer',
  'atl-mixer-bw',
  'duolingo-panel',
  'peach-hacks',
  'kickoff',
  'speaker',
  'summit-group',
  'summit-d2',
  'nationals-hero',
  'summit-d1',
  'summit-d2-crowd',
  'students-hero',
] as const;
