/**
 * Generates the background mosaic tiles for the auth pages.
 *
 * One tile per photo, smart-cropped. An earlier version cut a grid of crops out
 * of each source to pad the count out; it looked bad, because slicing a photo on
 * a blind grid halves faces and grabs empty background. If the wall needs fewer
 * repeats, make the tiles bigger (fewer slots to fill), do not cut more crops.
 *
 * Sources are the chapter's own photos plus a few ColorStack nationals shots.
 * Deliberately no headshots: portrait crops read as mugshots at tile size.
 *
 * Output is versioned (mosaic/v1) because vercel.json serves it immutable for a
 * year. Regenerating with different content means bumping to v2, not overwriting.
 *
 * Run from the repo root:  node scripts/build-mosaic.mjs
 */
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const VERSION = 'v1';
const SITE = path.resolve('../cs-gsu_official_website/public/images');
const VENDORED = path.resolve('source-photos'); // pulled from colorstack.org, kept out of public/
const OUT_DIR = path.resolve('public/images/mosaic', VERSION);
const MANIFEST = path.resolve('src/components/mosaicTiles.ts');

// Tiles render around 300px wide. 480 keeps them crisp on a 2x display, and they
// sit behind a blur and a wash so there is no reason to go higher.
const TILE = 480;
const QUALITY = 66;

/** [absolute source path, output name] */
const SOURCES = [
  // Chapter
  [path.join(SITE, '1.jpg'), 'chapter-group'],
  [path.join(SITE, 'student_page_img.jpg'), 'chapter-students'],
  [path.join(SITE, 'events/atl-social-mixer.png'), 'atl-mixer'],
  [path.join(SITE, 'events/atl-social-mixer-bw.jpg'), 'atl-mixer-bw'],
  [path.join(SITE, 'events/duolingo-panel.png'), 'duolingo-panel'],
  [path.join(SITE, 'events/peach-hacks.jpeg'), 'peach-hacks'],
  [path.join(SITE, 'involvement/kickoff-event.png'), 'kickoff'],
  [path.join(SITE, 'profiles/Daniel-Blackburn.jpg'), 'speaker'],
  // ColorStack nationals
  [path.join(SITE, '67133ca88dea988c2acca64c_summit group photo.jpg'), 'summit-group'],
  [path.join(SITE, '67c77e5e4c5aac70963df60e_ColorStack-Annual-Summit-D2-Chloe-Jackman-Photography-2024-272_websize.jpg'), 'summit-d2'],
  [path.join(SITE, '620cee9e7c4ce00022bd325a_ColorStack home hero-min.jpg'), 'nationals-hero'],
  [path.join(VENDORED, 'cs-01.jpg'), 'summit-d1'],
  [path.join(VENDORED, 'cs-02.jpg'), 'summit-d2-crowd'],
  [path.join(VENDORED, 'cs-03.jpg'), 'students-hero'],
];

await rm(path.resolve('public/images/mosaic'), { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

const names = [];
for (const [src, name] of SOURCES) {
  try {
    await stat(src);
  } catch {
    console.warn(`skip (missing): ${src}`);
    continue;
  }

  await sharp(src)
    // 'attention' picks the busiest region, which on these photos is the people.
    .resize(TILE, TILE, { fit: 'cover', position: 'attention' })
    .webp({ quality: QUALITY })
    .toFile(path.join(OUT_DIR, `${name}.webp`));
  names.push(name);
}

const sizes = await Promise.all(names.map(async (n) => (await stat(path.join(OUT_DIR, `${n}.webp`))).size));
const total = sizes.reduce((a, b) => a + b, 0);

await writeFile(
  MANIFEST,
  `// GENERATED by scripts/build-mosaic.mjs. Do not edit by hand.\n` +
    `// ${names.length} tiles, ${Math.round(total / 1024)} KB total.\n\n` +
    `export const MOSAIC_VERSION = '${VERSION}';\n\n` +
    `export const MOSAIC_TILES = [\n${names.map((n) => `  '${n}',`).join('\n')}\n] as const;\n`,
  'utf8'
);

console.log(`${names.length} tiles, ${Math.round(total / 1024)} KB total -> ${VERSION}`);
